[build]
buildCommand = "npm install && npm run server:build"

[deploy]
startCommand = "node dist/api/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
